### ISSUE TITLE
How to build the FactsSheets?

### ISSUE THREAD

**Issue by darapenhchet** [ria-ee/X-Road-opmonitor#6]
Dear XRoad:

I want to ask about how to build the factsheets like this? https://www.x-tee.ee/factsheets/EE/

Could you show me some instructions about it?

Best Regards, 
Dara Penhchet

**Comment by ToomasMolder** [comment]
Dear Dara

The Factsheet module is Estonian specific (incl X-tee older versions still in use) and is therefor not public in source code and/or installation procedures level.

Please find some principles here:
- it consists of one html (index.html in two languages) and set of stylesheets (.css) combined with calculation javascripts (.js) and base data file (.json);
- base data file is compiled by the system regularly (monthly) as one type of report, it includes necessary general values (like  "affected_parties": 52000, "effective_query_minutes": 15,    "effective_query_proportion": 0.03, "last_incident", "last_update", "name_eng",  "name_est", "protocol_changes": 4) as well as stats for every month of every year (like query_count, secsrv_count, subsystem_count, service_count, member_count, producer_count, gov_member_count, producers_top, etc);
- calculation javascript reads the base data file (In Estonia-specific case combines data from different versions statistics), finds sum of query_count over all months available (Requests to date), sum of query_count of previous year (Previous year), consecutive days of smooth X-Road experience in Estonia, etc, does all other necessary calculations and gives it to over div, id, span etc techniques to html;

With regards,
Toomas Mölder

**Comment by darapenhchet** [comment]
Dear @ToomasMolder ,
Thanks for your help. Right now I can collect the data from the Security Server. and could you share me how to calculate or query with MongoDB or PostgreSQL to get the information like fastsheet https://www.x-tee.ee/factsheets/EE/?

Best Regards,
Dara Penhchet
